
package vistas2;

import tp7.grupo6.Materia;

public class Menu extends javax.swing.JFrame {

    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemFormMaterias = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemFormAlumnos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemManejoInscripciones = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItemManipularNotas = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItemListadoAlumnos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSalir);

        jMenuBar2.add(jMenu1);

        jMenu2.setText("Materias");

        jMenuItemFormMaterias.setText("Formulario de Materias");
        jMenuItemFormMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormMateriasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemFormMaterias);

        jMenuBar2.add(jMenu2);

        jMenu3.setText("Alumnos");

        jMenuItemFormAlumnos.setText("Formulario de Alumnos");
        jMenuItemFormAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFormAlumnosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemFormAlumnos);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Inscripciones");

        jMenuItemManejoInscripciones.setText("Manejo de Inscripciones");
        jMenuItemManejoInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManejoInscripcionesActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemManejoInscripciones);

        jMenuBar2.add(jMenu4);

        jMenu7.setText("Carga de Notas");

        jMenuItemManipularNotas.setText("Manipulacion de Notas");
        jMenu7.add(jMenuItemManipularNotas);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Consultas");

        jMenuItemListadoAlumnos.setText("Listado de Alumnos x Materia");
        jMenu8.add(jMenuItemListadoAlumnos);

        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    private void jMenuItemFormMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormMateriasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();//removemos todo
        escritorio.repaint();
        ViewFormMaterias vfm=new ViewFormMaterias();//crer nueva ventana
        vfm.setVisible(true);//hacerla visible
        escritorio.add(vfm);//agregarla al escritorio
        escritorio.moveToFront(vfm);//llevarla al frente
    }//GEN-LAST:event_jMenuItemFormMateriasActionPerformed

    private void jMenuItemManejoInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManejoInscripcionesActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();//removemos todo
        escritorio.repaint();
        ViewFormInscripcion vfi= new ViewFormInscripcion();//crer nueva ventana
        vfi.setVisible(true);//hacerla visible
        escritorio.add(vfi);//agregarla al escritorio
        escritorio.moveToFront(vfi);//llevarla al frente
    }//GEN-LAST:event_jMenuItemManejoInscripcionesActionPerformed

    private void jMenuItemFormAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFormAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();//removemos todo
        escritorio.repaint();
        ViewFormAlumnos vfa= new ViewFormAlumnos();//crer nueva ventana
        vfa.setVisible(true);//hacerla visible
        escritorio.add(vfa);//agregarla al escritorio
        escritorio.moveToFront(vfa);//llevarla al frente
    }//GEN-LAST:event_jMenuItemFormAlumnosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemFormAlumnos;
    private javax.swing.JMenuItem jMenuItemFormMaterias;
    private javax.swing.JMenuItem jMenuItemListadoAlumnos;
    private javax.swing.JMenuItem jMenuItemManejoInscripciones;
    private javax.swing.JMenuItem jMenuItemManipularNotas;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JPopupMenu jPopupMenu1;
    // End of variables declaration//GEN-END:variables
}
